name: jira-log-processor

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/npm@1.0.0
      args: install
    - uses: actions/npm@1.0.0
      args: run build
