name: jira-log-processor

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-node@v1
      with:
        node-version: '8.0.0'

    - run: npm install

    - run: npm run build
