name: jira-log-processor

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
#     - name: 'Install Homebrew'
#       run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: 'Install Xamarin tools'
      run: |
        wget -q https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d15-9/62840955457733add681d6d929e5b618292e07df/43/package/xamarin.mac-5.2.1.9.pkg
        sudo installer -verbose -pkg xamarin.mac-5.2.1.9.pkg -target /
    - name: 'list'
      run: ll
