name: jira-log-processor

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
    # https://go.microsoft.com/fwlink/?linkid=871629
    - name: 'Select Xamarin SDK version'
      run: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1'
